version: '3.1'
services:
  web:
    build: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./app:/app
    ports:
      - "8555:80"
    environment:
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    # command: flask run --host=0.0.0.0 --port=80
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; donemage: postgresql10.1/alpine:latest
    links:
      - db
  db:
    image: postgresql10.1/alpine:latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./app/db/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'DhjnYjub2018Ufls'

